### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by MajesticKhan** [MajesticKhan/Nowcasting-Python#1]
### Unit testing
- [ ]  Create unit test to ensure python model is working properly

### Graphs and formatting
- [x] Plotting graphs: finished plotting graphs for example_dfm.py in [plot](https://github.com/MajesticKhan/Nowcasting-Python/tree/plot)
- [x] Plot loglik in Plotly
- Branch plot has been merged to the master. Should be able to see the graphs that are show in the Matlab code.

#### Comments:
- Next set of tasks is working on creating unit tests

**Comment by weu39843** [comment]
Looking forward for a new update!

**Comment by MajesticKhan** [comment]
@weu39843 Its been busy for the past month. Apologies for the delay

**Comment by MajesticKhan** [comment]
Finished building the main structure of plotting graphs in example_dfm.py
Just need to add comments

I created a new branch called [plot](https://github.com/MajesticKhan/Nowcasting-Python/tree/plot) which contains the latest updates for generating plots.

I just need polish the code before merging it into the master branch.

The result should look like this:
<img width="1777" alt="image" src="https://user-images.githubusercontent.com/36779912/85243119-873dd000-b406-11ea-90b7-a3bedc31928d.png">
