### ISSUE TITLE
About update_Nowcast.py

### ISSUE THREAD

**Issue by WXZQuant** [MajesticKhan/Nowcasting-Python#3]
Thanks for sharing your code.
Recently I'm learning about nowcasting models, your code is just what I need.
But I got something wrong when running your update_Nowcast.py，so I tried to fix it.

When I change the vintage, I may got error on line 407 ~ line 422，so I rewrite like this

    for jk in range(1, lag + 1):

        Plag.append(np.zeros(Plag[0].shape))

        for jt in range(Plag[0].shape[0], lag, -1):

            As = np.matmul(np.matmul(Vf[jt-jk-1], A.T), np.linalg.pinv(np.matmul(np.matmul(A, Vf[jt-jk-1]), A.T) + Q))

            Plag[jk][jt-1] = np.matmul(As, Plag[jk-1][jt-1]) 

Also you mention that weight seems suspicious.
I find a mistake on line 281，it should be
`if t_miss[j] > t_miss[i]:`

I'm not sure whether line 245 should like this
`m = max(t_miss[i],t_fcst[0])`

Finally, I run the code with vintage_old = '2016-11-30' and vintage_new = '2016-12-23'.
I can get these：

              2016-11-30 nowcast:              2.80471
      Impact from data revisions:      0.10666
       Impact from data releases:      -0.49701
                                     +_________
                    Total impact:      -0.39035
              2016-12-23 nowcast:              2.41436

**Comment by MajesticKhan** [comment]
Good catch!!

Do me a favor and create a pull request! I have been bogged down with other stuff and I haven't gotten to fully experiment with other dates.

I'll take a closer look at your pr later this week!

Thanks for this!

**Comment by MajesticKhan** [comment]
@WXZQuant I'll take a closer look at lines 407 through 422

**Comment by MajesticKhan** [comment]
@WXZQuant Thanks for spotting this. This could have been caught if I implemented a couple of checks. My apologies.

Thanks again!

EDIT: 
also apologies, for asking a pull request. I wanted to get a fix in asap and was curious if there was anything else that was causing a hiccup.

**Comment by WXZQuant** [comment]
Sorry for the late reply, I'm not always online.
You've nothing to apologize for, I really learn a lot from your code. We just learn and share from each other. 
Glad to contribute to the project :）
